### ISSUE TITLE
debug: true is not working

### ISSUE THREAD

**Issue by miparnisari** [c0b41/gulp-apidoc#13]
This is my gulpfile:

```javascript
gulp.task('apidoc', function(done){
  apidoc({
    src: "./endpoints",
    dest: "./doc",
    debug: true,
  }, done);
})
```

This is my output: 

```javascript
$ gulp apidoc
[16:53:31] Using gulpfile ~\Documents\app\api\gulpfile.js
[16:53:31] Starting 'apidoc'...
[16:53:31] 'apidoc' errored after 104 ms
[16:53:31] Error in plugin 'gulp-apidoc'
Message:
    Execution terminated (set " debug: true " in gulpfile.js for details.
```

**Comment by c0b41** [comment]
Hey can you share example folder?

**Comment by flynnshu** [comment]
I'm having the same issues. 

gulp.task('apidoc', function (done) {
    apidoc({
        debug:true,
        src: "../cc-api/src",
        dest: "apidoc/",
        debug: true
    }, done);
});

[20:33:15] Starting 'apidoc'...
[20:33:15] 'apidoc' errored after 136 ms
[20:33:15] Error in plugin 'gulp-apidoc'
Message:
    Execution terminated (set " debug: true " in gulpfile.js for details. 

Process finished with exit code 1

**Comment by c0b41** [comment]
@miparnisari  @flynnshu I'm sorry about that, now update your gulp-apidoc, also use [slient option](https://github.com/c0b41/gulp-apidoc#optionssilent)
