### ISSUE TITLE
Problems with client js loading

### ISSUE THREAD

**Issue by shekspir55** [c0b41/gulp-apidoc#15]
```ReferenceError: require is not defined```
And no js loads, I think this is because of the versions of require.js . But when I change `require` to `requirejs` i get this
```
ReferenceError: assignment to undeclared variable index   locale.js:8:1
TypeError: c is undefined                         require.min.js:44:7
TypeError: this is undefined                     diff_match_patch.min.js:322:3
TypeError: c is undefined
``` 
But I think, this is core apidoc issue rather than yours.

**Comment by c0b41** [comment]
seems like a not gulp-apidoc problem, maybe can you share git projet ?

**Comment by shekspir55** [comment]
Oh sorry, my bad, I've done something wrong.

**Comment by shekspir55** [comment]
Problem was with babel.js, thank you for this repo.

**Comment by c0b41** [comment]
@shekspir55 :+1:
