### ISSUE TITLE
"apidoc.json" not loaded.

### ISSUE THREAD

**Issue by godong9** [c0b41/gulp-apidoc#17]
I want load "apidoc.json" file when I make apidoc.

When I use apidoc command, that working. But, gulp-apidoc is not working.

**Comment by c0b41** [comment]
@godong9 can you share example code?

**Comment by godong9** [comment]
https://github.com/Nexters/cardfactory

In cardfactory directory, "apidoc" command is working.

But, gulp api-doc is not working.

**Comment by c0b41** [comment]
@godong9 sorry about that, two way the fixed this problem..

1.Apidoc.json moved to routers directory
or
2.Gulpfile.js set gulp-apidoc config

```js
var apidocConf = {
  src: "routes/",
  dest: "doc/",
  config: "./"       // root dir
  debug: true
};

```

**Comment by godong9** [comment]
Thanks very much!
