### ISSUE TITLE
apidoc.json not found when config set to "./apidoc.json" 

### ISSUE THREAD

**Issue by deusofnull** [c0b41/gulp-apidoc#18]
Hey everyone, 

Just found a slightly confusing bug / issue that might happen to others.  I have figured out the issue and am here to recommend making the solution more explicit / fixing the issue that caused my confusion.

I had set my gulpfile's apidoc task like this: 
```
gulp.task("apidoc", function(done){
  apidoc({
    src: "app/",
    dest: "../docs/",
    debug: true,
    config: "./apidoc.json"
  }, done);
});
```

I figured that the `config: "./apidoc.json"` would point to the apidoc.json configuration file which was in the same directory as my gulpfile.  However, it didn't, returning this error 
```
[11:47:21] Using gulpfile ~/codes/.../.../laravel/gulpfile.js
[11:47:21] Starting 'apidoc'...
debug: apidoc.json/package.json not found!
debug: apidoc.json/apidoc.json not found!
```

I ended up figuring out that the config flag for apidoc's constructor in the gulp task had to be set to what I suppose is the _location or directory_ where the `apidoc.json` file is located. 

So, to fix it, I had to set the config flag to just `config: "./"`.  

This was confusing to me and would probably be a quick fix.  

I'll try and take a look at how the config file gets pulled in and perhaps make a pull request.  

Thanks for the excellent package!  This is by no means a big issue, just something that could be streamlined.

**Comment by c0b41** [comment]
@deusofnull Actually config parameter file, must be directory.. So this not bugs :)

[ref 1](https://github.com/apidoc/apidoc/blob/master/lib/index.js#L21) [ref 2](https://github.com/c0b41/gulp-apidoc#optionsconfig)
