### ISSUE TITLE
Interface are not generate correctly.

### ISSUE THREAD

**Issue by umair-khanzada** [c0b41/gulp-apidoc#23]
Didn't create form, input fields, buttons.

When I generate api documentation using this module it's generate only documentation and didn't provide interface to interact with api's. but when I generate manually using apidoc command <br /> `apidoc -i myapp/ -o apidoc/ ` it's generate perfectly.

**Comment by c0b41** [comment]
@umair-khanzada can you share any example?

**Comment by umair-khanzada** [comment]
Sure!
Old one with `grunt apidoc` [go clean app](https://greencommunitylaundry.herokuapp.com/api)
new 
![screenshot](https://cloud.githubusercontent.com/assets/8782817/24549870/d7e6aa7c-1634-11e7-9fe6-cd701845cfbf.png)
see here is not a form for login.

**Comment by c0b41** [comment]
@umair-khanzada I do not know maybe there might be a problem with your settings, but example working very well
![image](https://cloud.githubusercontent.com/assets/2834954/24550436/afe181e0-1626-11e7-8bb2-9c897c8830c6.png)

**Comment by umair-khanzada** [comment]
Yes you are right documentation works fine but the issue is didn't generate forms, and form's element for interact with api.

![old](https://cloud.githubusercontent.com/assets/8782817/24551127/b1cdab1e-163a-11e7-8f65-5d640c944f83.png)

**Comment by c0b41** [comment]
@umair-khanzada Did you define two values? [options](https://github.com/apidoc/apidoc/blob/master/example/apidoc.json#L6-L7)

**Comment by umair-khanzada** [comment]
Yeah it's same like apidoc.json
```
{
  "name": "Nazli Trading",
  "version": "0.0.1",
  "description": "Nazli Trading APi",
  "title": "Nazli",
  "url": "http://localhost:9000/api",
  "sampleUrl": "http://localhost:9000/api",
  "header": {
    "title": "Api Endpoints",
    "filename": "header.md"
  },
  "footer": {
    "title": "My own footer title",
    "filename": "footer.md"
  },
  "template": {
    "withCompare": true,
    "withGenerator": true
  }
}
```

**Comment by c0b41** [comment]
@umair-khanzada can you install new patch version `yarn add gulp-apidoc@latest`

**Comment by umair-khanzada** [comment]
Okie

Thank you for your reply  =D
