### ISSUE TITLE
how to configure apidoc 

### ISSUE THREAD

**Issue by wuchuguang** [c0b41/gulp-apidoc#25]
--parse-filters         Optional user defined filters. Format name=filename
   --parse-languages       Optional user defined languages. Format name=filename
   --parse-parsers         Optional user defined parsers. Format name=filename
   --parse-workers         Optional user defined workers. Format name=filename

**Comment by c0b41** [comment]
I dont see any command for apidoc ? http://apidocjs.com/#CLI
