### ISSUE TITLE
Fix bug create doc

### ISSUE THREAD

**Issue by tungjs** [c0b41/gulp-apidoc#26]
Hi there,

when i use lib i seen a bug, i can't create document.
https://github.com/c0b41/gulp-apidoc/blob/master/index.js#L24
Please change `var chunk = apidoc.createDoc(_opt);` to `var chunk = apidoc(_opt);`

**Comment by c0b41** [comment]
@tungjs i dont see any errors? also [#L172-L174](https://github.com/apidoc/apidoc/blob/master/lib/index.js#L172-L174)

**Comment by c0b41** [comment]
@tungjs also what errors?
