### ISSUE TITLE
Exclude nested node_modules

### ISSUE THREAD

**Issue by xavicolomer** [c0b41/gulp-apidoc#27]
Hi there!

How can I exclude node_modules (sometimes nested) from the apidoc logic?

Thanks!

**Comment by c0b41** [comment]
@xavicolomer https://github.com/apidoc/apidoc/issues/6#issuecomment-17991722

**Comment by xavicolomer** [comment]
This configuration worked for me.

```
apidoc({
    src: 'path/to/api/docs',
    dest: 'docs/api',
    debug: true,
    includeFilters: [ '.*\\.js$' ],
    excludeFilters: [ 'node_modules' ]
  }, done);
```
