### ISSUE TITLE
Seemed that not work with gulp 4

### ISSUE THREAD

**Issue by mishelen** [c0b41/gulp-apidoc#28]
It pretty work untill I have to move to gulp 4. So may be some problem with task declaration in my code.

Im just redefine in new callback style of gulp 4: 
```js
gulp.task('apidoc', done => {
  apidoc({ src: 'src/', dest: 'build/doc', done);
  done();
});
```
But everytimes I get async errors: 

```
error: Undefined error. 
{ File: './node_modules/ultron/index.js',
  Block: 2,
  Element: '@constructor',
  Source: '@constructor\n@param {EventEmitter} 
ee EventEmitter instance we need to wrap.' }
error Command failed with exit code 1.
```
No matter if I add or not this `done` in end of task. Or remove it as callback for `apidock` function.

But when I run this script in **parallel** with main thread of tasks like this
```js
gulp.task('default',
    gulp.parallel('compile', 'apidoc')
);
```
everything is fine.

**Comment by c0b41** [comment]
I will check it out

**Comment by c0b41** [comment]
@mishelen probably your src folder path not working, i am not any see problem gulp4
Also

```js
gulp.task('apidoc', done => {
  apidoc({ src: './src', dest: './build/doc'}, done);
});
```
