### ISSUE TITLE
multiple folders for src

### ISSUE THREAD

**Issue by adrianvlupu** [c0b41/gulp-apidoc#8]
Hi,

In the 0.1.5 version the src parameter could be an array. That was really useful in case the api was spread across multiple folders. Is there any way to do that in this version?

Great module btw

**Comment by ayhankuru** [comment]
Thank you, I will work on this subject over

**Comment by rzani** [comment]
With this change the apidoc.json should be accompanied by the src?
Until now,  gulp-apidoc consider the apidoc.json in the same path of gulpfile.json.

**Comment by ayhankuru** [comment]
@rzani apidoc.json must be src folder, and apidoc.jo does not have the package.json apidoc parsed name, desc vs.
